name: sasomtam
version: 0.1.6
summary: Card rewards system
description: Card rewards system

confinement: strict
base: core18
grade: stable

apps:
  sasomtam:
    command: sasomtam
    extensions: [flutter-master]
    plugs:
    - network
    slots:
      - dbus-sasomtam

parts:
  sasomtam:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

slots:
  dbus-sasomtam:
    interface: dbus
    bus: session
    name: com.shanuy.sasomtam

  
